### ISSUE TITLE
Qual framework foi utilizada?

### ISSUE THREAD

**Issue by NataliaCarvalho03** [viniciusmo/memory-game#1]
Tudo bem? Estou estudando desenvolvimento web e seu jogo vai me ajudar bastante. Só queria saber se você utilizou algum framework pra faze-lo. Comecei o meu e as linhas de código ja estão bem extensas, o seu me chamou atenção por ter menos código. Obrigada.

**Comment by viniciusmo** [comment]
Oi @NataliaCarvalho03 , não utilizei nenhum framework ;).
